#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lessonweb.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lessontrack")]
	public partial class DBClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEndorsement(Endorsement instance);
    partial void UpdateEndorsement(Endorsement instance);
    partial void DeleteEndorsement(Endorsement instance);
    partial void InsertAircraft(Aircraft instance);
    partial void UpdateAircraft(Aircraft instance);
    partial void DeleteAircraft(Aircraft instance);
    partial void InsertFAACert(FAACert instance);
    partial void UpdateFAACert(FAACert instance);
    partial void DeleteFAACert(FAACert instance);
    partial void InsertLESSONITEM(LESSONITEM instance);
    partial void UpdateLESSONITEM(LESSONITEM instance);
    partial void DeleteLESSONITEM(LESSONITEM instance);
    partial void InsertLESSON(LESSON instance);
    partial void UpdateLESSON(LESSON instance);
    partial void DeleteLESSON(LESSON instance);
    partial void InsertSTAGE(STAGE instance);
    partial void UpdateSTAGE(STAGE instance);
    partial void DeleteSTAGE(STAGE instance);
    partial void InsertCompletionLog(CompletionLog instance);
    partial void UpdateCompletionLog(CompletionLog instance);
    partial void DeleteCompletionLog(CompletionLog instance);
    partial void InsertAppUser(AppUser instance);
    partial void UpdateAppUser(AppUser instance);
    partial void DeleteAppUser(AppUser instance);
    #endregion
		
		public DBClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["lessontrackConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Endorsement> Endorsements
		{
			get
			{
				return this.GetTable<Endorsement>();
			}
		}
		
		public System.Data.Linq.Table<Aircraft> Aircrafts
		{
			get
			{
				return this.GetTable<Aircraft>();
			}
		}
		
		public System.Data.Linq.Table<FAACert> FAACerts
		{
			get
			{
				return this.GetTable<FAACert>();
			}
		}
		
		public System.Data.Linq.Table<LESSONITEM> LESSONITEMs
		{
			get
			{
				return this.GetTable<LESSONITEM>();
			}
		}
		
		public System.Data.Linq.Table<LESSON> LESSONs
		{
			get
			{
				return this.GetTable<LESSON>();
			}
		}
		
		public System.Data.Linq.Table<STAGE> STAGEs
		{
			get
			{
				return this.GetTable<STAGE>();
			}
		}
		
		public System.Data.Linq.Table<CompletionLog> CompletionLogs
		{
			get
			{
				return this.GetTable<CompletionLog>();
			}
		}
		
		public System.Data.Linq.Table<AppUser> AppUsers
		{
			get
			{
				return this.GetTable<AppUser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Endorsements")]
	public partial class Endorsement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserEmail;
		
		private string _EndorsementType;
		
		private string _EndorsementSubtype;
		
		private System.Nullable<System.DateTime> _ValidityIfAny;
		
		private System.DateTime _IssuedOn;
		
		private string _IssuingAuthority;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnEndorsementTypeChanging(string value);
    partial void OnEndorsementTypeChanged();
    partial void OnEndorsementSubtypeChanging(string value);
    partial void OnEndorsementSubtypeChanged();
    partial void OnValidityIfAnyChanging(System.Nullable<System.DateTime> value);
    partial void OnValidityIfAnyChanged();
    partial void OnIssuedOnChanging(System.DateTime value);
    partial void OnIssuedOnChanged();
    partial void OnIssuingAuthorityChanging(string value);
    partial void OnIssuingAuthorityChanged();
    #endregion
		
		public Endorsement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserEmail
		{
			get
			{
				return this._UserEmail;
			}
			set
			{
				if ((this._UserEmail != value))
				{
					this.OnUserEmailChanging(value);
					this.SendPropertyChanging();
					this._UserEmail = value;
					this.SendPropertyChanged("UserEmail");
					this.OnUserEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndorsementType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EndorsementType
		{
			get
			{
				return this._EndorsementType;
			}
			set
			{
				if ((this._EndorsementType != value))
				{
					this.OnEndorsementTypeChanging(value);
					this.SendPropertyChanging();
					this._EndorsementType = value;
					this.SendPropertyChanged("EndorsementType");
					this.OnEndorsementTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndorsementSubtype", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EndorsementSubtype
		{
			get
			{
				return this._EndorsementSubtype;
			}
			set
			{
				if ((this._EndorsementSubtype != value))
				{
					this.OnEndorsementSubtypeChanging(value);
					this.SendPropertyChanging();
					this._EndorsementSubtype = value;
					this.SendPropertyChanged("EndorsementSubtype");
					this.OnEndorsementSubtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidityIfAny", DbType="Date")]
		public System.Nullable<System.DateTime> ValidityIfAny
		{
			get
			{
				return this._ValidityIfAny;
			}
			set
			{
				if ((this._ValidityIfAny != value))
				{
					this.OnValidityIfAnyChanging(value);
					this.SendPropertyChanging();
					this._ValidityIfAny = value;
					this.SendPropertyChanged("ValidityIfAny");
					this.OnValidityIfAnyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssuedOn", DbType="Date NOT NULL")]
		public System.DateTime IssuedOn
		{
			get
			{
				return this._IssuedOn;
			}
			set
			{
				if ((this._IssuedOn != value))
				{
					this.OnIssuedOnChanging(value);
					this.SendPropertyChanging();
					this._IssuedOn = value;
					this.SendPropertyChanged("IssuedOn");
					this.OnIssuedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IssuingAuthority", DbType="NVarChar(50)")]
		public string IssuingAuthority
		{
			get
			{
				return this._IssuingAuthority;
			}
			set
			{
				if ((this._IssuingAuthority != value))
				{
					this.OnIssuingAuthorityChanging(value);
					this.SendPropertyChanging();
					this._IssuingAuthority = value;
					this.SendPropertyChanged("IssuingAuthority");
					this.OnIssuingAuthorityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aircrafts")]
	public partial class Aircraft : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TailNumber;
		
		private string _Make;
		
		private string _Model;
		
		private string _Year;
		
		private System.Nullable<decimal> _LastHobbs;
		
		private System.Nullable<decimal> _LastMXHobbs;
		
		private int _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTailNumberChanging(string value);
    partial void OnTailNumberChanged();
    partial void OnMakeChanging(string value);
    partial void OnMakeChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnLastHobbsChanging(System.Nullable<decimal> value);
    partial void OnLastHobbsChanged();
    partial void OnLastMXHobbsChanging(System.Nullable<decimal> value);
    partial void OnLastMXHobbsChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    #endregion
		
		public Aircraft()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TailNumber", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TailNumber
		{
			get
			{
				return this._TailNumber;
			}
			set
			{
				if ((this._TailNumber != value))
				{
					this.OnTailNumberChanging(value);
					this.SendPropertyChanging();
					this._TailNumber = value;
					this.SendPropertyChanged("TailNumber");
					this.OnTailNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Make", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Make
		{
			get
			{
				return this._Make;
			}
			set
			{
				if ((this._Make != value))
				{
					this.OnMakeChanging(value);
					this.SendPropertyChanging();
					this._Make = value;
					this.SendPropertyChanged("Make");
					this.OnMakeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NChar(10)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastHobbs", DbType="Decimal(7,1)")]
		public System.Nullable<decimal> LastHobbs
		{
			get
			{
				return this._LastHobbs;
			}
			set
			{
				if ((this._LastHobbs != value))
				{
					this.OnLastHobbsChanging(value);
					this.SendPropertyChanging();
					this._LastHobbs = value;
					this.SendPropertyChanged("LastHobbs");
					this.OnLastHobbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastMXHobbs", DbType="Decimal(7,1)")]
		public System.Nullable<decimal> LastMXHobbs
		{
			get
			{
				return this._LastMXHobbs;
			}
			set
			{
				if ((this._LastMXHobbs != value))
				{
					this.OnLastMXHobbsChanging(value);
					this.SendPropertyChanging();
					this._LastMXHobbs = value;
					this.SendPropertyChanged("LastMXHobbs");
					this.OnLastMXHobbsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FAACerts")]
	public partial class FAACert : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CertificationID;
		
		private string _CertificationName;
		
		private string _InfoLink;
		
		private string _FAAPart;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCertificationIDChanging(string value);
    partial void OnCertificationIDChanged();
    partial void OnCertificationNameChanging(string value);
    partial void OnCertificationNameChanged();
    partial void OnInfoLinkChanging(string value);
    partial void OnInfoLinkChanged();
    partial void OnFAAPartChanging(string value);
    partial void OnFAAPartChanged();
    #endregion
		
		public FAACert()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificationID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CertificationID
		{
			get
			{
				return this._CertificationID;
			}
			set
			{
				if ((this._CertificationID != value))
				{
					this.OnCertificationIDChanging(value);
					this.SendPropertyChanging();
					this._CertificationID = value;
					this.SendPropertyChanged("CertificationID");
					this.OnCertificationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificationName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CertificationName
		{
			get
			{
				return this._CertificationName;
			}
			set
			{
				if ((this._CertificationName != value))
				{
					this.OnCertificationNameChanging(value);
					this.SendPropertyChanging();
					this._CertificationName = value;
					this.SendPropertyChanged("CertificationName");
					this.OnCertificationNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoLink", DbType="NVarChar(500)")]
		public string InfoLink
		{
			get
			{
				return this._InfoLink;
			}
			set
			{
				if ((this._InfoLink != value))
				{
					this.OnInfoLinkChanging(value);
					this.SendPropertyChanging();
					this._InfoLink = value;
					this.SendPropertyChanged("InfoLink");
					this.OnInfoLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAAPart", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string FAAPart
		{
			get
			{
				return this._FAAPart;
			}
			set
			{
				if ((this._FAAPart != value))
				{
					this.OnFAAPartChanging(value);
					this.SendPropertyChanging();
					this._FAAPart = value;
					this.SendPropertyChanged("FAAPart");
					this.OnFAAPartChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LESSONITEMS")]
	public partial class LESSONITEM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LineID;
		
		private int _LESSONID;
		
		private int _STAGEID;
		
		private string _LESSONGUID;
		
		private string _ItemName;
		
		private bool _IsGroup;
		
		private bool _IsReview;
		
		private bool _IsIntro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLineIDChanging(int value);
    partial void OnLineIDChanged();
    partial void OnLESSONIDChanging(int value);
    partial void OnLESSONIDChanged();
    partial void OnSTAGEIDChanging(int value);
    partial void OnSTAGEIDChanged();
    partial void OnLESSONGUIDChanging(string value);
    partial void OnLESSONGUIDChanged();
    partial void OnItemNameChanging(string value);
    partial void OnItemNameChanged();
    partial void OnIsGroupChanging(bool value);
    partial void OnIsGroupChanged();
    partial void OnIsReviewChanging(bool value);
    partial void OnIsReviewChanged();
    partial void OnIsIntroChanging(bool value);
    partial void OnIsIntroChanged();
    #endregion
		
		public LESSONITEM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LineID
		{
			get
			{
				return this._LineID;
			}
			set
			{
				if ((this._LineID != value))
				{
					this.OnLineIDChanging(value);
					this.SendPropertyChanging();
					this._LineID = value;
					this.SendPropertyChanged("LineID");
					this.OnLineIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LESSONID", DbType="Int NOT NULL")]
		public int LESSONID
		{
			get
			{
				return this._LESSONID;
			}
			set
			{
				if ((this._LESSONID != value))
				{
					this.OnLESSONIDChanging(value);
					this.SendPropertyChanging();
					this._LESSONID = value;
					this.SendPropertyChanged("LESSONID");
					this.OnLESSONIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAGEID", DbType="Int NOT NULL")]
		public int STAGEID
		{
			get
			{
				return this._STAGEID;
			}
			set
			{
				if ((this._STAGEID != value))
				{
					this.OnSTAGEIDChanging(value);
					this.SendPropertyChanging();
					this._STAGEID = value;
					this.SendPropertyChanged("STAGEID");
					this.OnSTAGEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LESSONGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LESSONGUID
		{
			get
			{
				return this._LESSONGUID;
			}
			set
			{
				if ((this._LESSONGUID != value))
				{
					this.OnLESSONGUIDChanging(value);
					this.SendPropertyChanging();
					this._LESSONGUID = value;
					this.SendPropertyChanged("LESSONGUID");
					this.OnLESSONGUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ItemName
		{
			get
			{
				return this._ItemName;
			}
			set
			{
				if ((this._ItemName != value))
				{
					this.OnItemNameChanging(value);
					this.SendPropertyChanging();
					this._ItemName = value;
					this.SendPropertyChanged("ItemName");
					this.OnItemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGroup", DbType="Bit NOT NULL")]
		public bool IsGroup
		{
			get
			{
				return this._IsGroup;
			}
			set
			{
				if ((this._IsGroup != value))
				{
					this.OnIsGroupChanging(value);
					this.SendPropertyChanging();
					this._IsGroup = value;
					this.SendPropertyChanged("IsGroup");
					this.OnIsGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReview", DbType="Bit NOT NULL")]
		public bool IsReview
		{
			get
			{
				return this._IsReview;
			}
			set
			{
				if ((this._IsReview != value))
				{
					this.OnIsReviewChanging(value);
					this.SendPropertyChanging();
					this._IsReview = value;
					this.SendPropertyChanged("IsReview");
					this.OnIsReviewChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsIntro", DbType="Bit NOT NULL")]
		public bool IsIntro
		{
			get
			{
				return this._IsIntro;
			}
			set
			{
				if ((this._IsIntro != value))
				{
					this.OnIsIntroChanging(value);
					this.SendPropertyChanging();
					this._IsIntro = value;
					this.SendPropertyChanged("IsIntro");
					this.OnIsIntroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LESSONS")]
	public partial class LESSON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LESSONID;
		
		private string _Title;
		
		private string _Objective;
		
		private string _Standard;
		
		private int _STAGEID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLESSONIDChanging(int value);
    partial void OnLESSONIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnObjectiveChanging(string value);
    partial void OnObjectiveChanged();
    partial void OnStandardChanging(string value);
    partial void OnStandardChanged();
    partial void OnSTAGEIDChanging(int value);
    partial void OnSTAGEIDChanged();
    #endregion
		
		public LESSON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LESSONID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LESSONID
		{
			get
			{
				return this._LESSONID;
			}
			set
			{
				if ((this._LESSONID != value))
				{
					this.OnLESSONIDChanging(value);
					this.SendPropertyChanging();
					this._LESSONID = value;
					this.SendPropertyChanged("LESSONID");
					this.OnLESSONIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objective", DbType="NVarChar(MAX)")]
		public string Objective
		{
			get
			{
				return this._Objective;
			}
			set
			{
				if ((this._Objective != value))
				{
					this.OnObjectiveChanging(value);
					this.SendPropertyChanging();
					this._Objective = value;
					this.SendPropertyChanged("Objective");
					this.OnObjectiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Standard", DbType="NVarChar(MAX)")]
		public string Standard
		{
			get
			{
				return this._Standard;
			}
			set
			{
				if ((this._Standard != value))
				{
					this.OnStandardChanging(value);
					this.SendPropertyChanging();
					this._Standard = value;
					this.SendPropertyChanged("Standard");
					this.OnStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAGEID", DbType="Int NOT NULL")]
		public int STAGEID
		{
			get
			{
				return this._STAGEID;
			}
			set
			{
				if ((this._STAGEID != value))
				{
					this.OnSTAGEIDChanging(value);
					this.SendPropertyChanging();
					this._STAGEID = value;
					this.SendPropertyChanged("STAGEID");
					this.OnSTAGEIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STAGES")]
	public partial class STAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAGEID;
		
		private string _Name;
		
		private string _Type;
		
		private string _Objective;
		
		private string _Standard;
		
		private string _CertificationID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAGEIDChanging(int value);
    partial void OnSTAGEIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnObjectiveChanging(string value);
    partial void OnObjectiveChanged();
    partial void OnStandardChanging(string value);
    partial void OnStandardChanged();
    partial void OnCertificationIDChanging(string value);
    partial void OnCertificationIDChanged();
    #endregion
		
		public STAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAGEID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAGEID
		{
			get
			{
				return this._STAGEID;
			}
			set
			{
				if ((this._STAGEID != value))
				{
					this.OnSTAGEIDChanging(value);
					this.SendPropertyChanging();
					this._STAGEID = value;
					this.SendPropertyChanged("STAGEID");
					this.OnSTAGEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Objective", DbType="VarChar(MAX)")]
		public string Objective
		{
			get
			{
				return this._Objective;
			}
			set
			{
				if ((this._Objective != value))
				{
					this.OnObjectiveChanging(value);
					this.SendPropertyChanging();
					this._Objective = value;
					this.SendPropertyChanged("Objective");
					this.OnObjectiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Standard", DbType="VarChar(MAX)")]
		public string Standard
		{
			get
			{
				return this._Standard;
			}
			set
			{
				if ((this._Standard != value))
				{
					this.OnStandardChanging(value);
					this.SendPropertyChanging();
					this._Standard = value;
					this.SendPropertyChanged("Standard");
					this.OnStandardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificationID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CertificationID
		{
			get
			{
				return this._CertificationID;
			}
			set
			{
				if ((this._CertificationID != value))
				{
					this.OnCertificationIDChanging(value);
					this.SendPropertyChanging();
					this._CertificationID = value;
					this.SendPropertyChanged("CertificationID");
					this.OnCertificationIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CompletionLogs")]
	public partial class CompletionLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.DateTime _DateCompleted;
		
		private string _Student;
		
		private string _Instructor;
		
		private string _AircraftUsed;
		
		private string _LessonGUID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDateCompletedChanging(System.DateTime value);
    partial void OnDateCompletedChanged();
    partial void OnStudentChanging(string value);
    partial void OnStudentChanged();
    partial void OnInstructorChanging(string value);
    partial void OnInstructorChanged();
    partial void OnAircraftUsedChanging(string value);
    partial void OnAircraftUsedChanged();
    partial void OnLessonGUIDChanging(string value);
    partial void OnLessonGUIDChanged();
    #endregion
		
		public CompletionLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCompleted", DbType="DateTime NOT NULL")]
		public System.DateTime DateCompleted
		{
			get
			{
				return this._DateCompleted;
			}
			set
			{
				if ((this._DateCompleted != value))
				{
					this.OnDateCompletedChanging(value);
					this.SendPropertyChanging();
					this._DateCompleted = value;
					this.SendPropertyChanged("DateCompleted");
					this.OnDateCompletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Student
		{
			get
			{
				return this._Student;
			}
			set
			{
				if ((this._Student != value))
				{
					this.OnStudentChanging(value);
					this.SendPropertyChanging();
					this._Student = value;
					this.SendPropertyChanged("Student");
					this.OnStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instructor", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Instructor
		{
			get
			{
				return this._Instructor;
			}
			set
			{
				if ((this._Instructor != value))
				{
					this.OnInstructorChanging(value);
					this.SendPropertyChanging();
					this._Instructor = value;
					this.SendPropertyChanged("Instructor");
					this.OnInstructorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AircraftUsed", DbType="NChar(10)")]
		public string AircraftUsed
		{
			get
			{
				return this._AircraftUsed;
			}
			set
			{
				if ((this._AircraftUsed != value))
				{
					this.OnAircraftUsedChanging(value);
					this.SendPropertyChanging();
					this._AircraftUsed = value;
					this.SendPropertyChanged("AircraftUsed");
					this.OnAircraftUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessonGUID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LessonGUID
		{
			get
			{
				return this._LessonGUID;
			}
			set
			{
				if ((this._LessonGUID != value))
				{
					this.OnLessonGUIDChanging(value);
					this.SendPropertyChanging();
					this._LessonGUID = value;
					this.SendPropertyChanged("LessonGUID");
					this.OnLessonGUIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AppUsers")]
	public partial class AppUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserEmail;
		
		private System.Data.Linq.Binary _PasswordHash;
		
		private bool _IsAdmin;
		
		private bool _IsStudent;
		
		private bool _IsInstructor;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _MI;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _CellPhone;
		
		private string _HomePhone;
		
		private string _WorkPhone;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _City;
		
		private string _State;
		
		private string _ZIP;
		
		private string _Country;
		
		private System.DateTime _CreatedOn;
		
		private string _Employer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserEmailChanging(string value);
    partial void OnUserEmailChanged();
    partial void OnPasswordHashChanging(System.Data.Linq.Binary value);
    partial void OnPasswordHashChanged();
    partial void OnIsAdminChanging(bool value);
    partial void OnIsAdminChanged();
    partial void OnIsStudentChanging(bool value);
    partial void OnIsStudentChanged();
    partial void OnIsInstructorChanging(bool value);
    partial void OnIsInstructorChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnMIChanging(string value);
    partial void OnMIChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    partial void OnHomePhoneChanging(string value);
    partial void OnHomePhoneChanged();
    partial void OnWorkPhoneChanging(string value);
    partial void OnWorkPhoneChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZIPChanging(string value);
    partial void OnZIPChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnEmployerChanging(string value);
    partial void OnEmployerChanged();
    #endregion
		
		public AppUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserEmail
		{
			get
			{
				return this._UserEmail;
			}
			set
			{
				if ((this._UserEmail != value))
				{
					this.OnUserEmailChanging(value);
					this.SendPropertyChanging();
					this._UserEmail = value;
					this.SendPropertyChanged("UserEmail");
					this.OnUserEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordHash", DbType="VarBinary(100)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PasswordHash
		{
			get
			{
				return this._PasswordHash;
			}
			set
			{
				if ((this._PasswordHash != value))
				{
					this.OnPasswordHashChanging(value);
					this.SendPropertyChanging();
					this._PasswordHash = value;
					this.SendPropertyChanged("PasswordHash");
					this.OnPasswordHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStudent", DbType="Bit NOT NULL")]
		public bool IsStudent
		{
			get
			{
				return this._IsStudent;
			}
			set
			{
				if ((this._IsStudent != value))
				{
					this.OnIsStudentChanging(value);
					this.SendPropertyChanging();
					this._IsStudent = value;
					this.SendPropertyChanged("IsStudent");
					this.OnIsStudentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsInstructor", DbType="Bit NOT NULL")]
		public bool IsInstructor
		{
			get
			{
				return this._IsInstructor;
			}
			set
			{
				if ((this._IsInstructor != value))
				{
					this.OnIsInstructorChanging(value);
					this.SendPropertyChanging();
					this._IsInstructor = value;
					this.SendPropertyChanged("IsInstructor");
					this.OnIsInstructorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MI", DbType="NVarChar(50)")]
		public string MI
		{
			get
			{
				return this._MI;
			}
			set
			{
				if ((this._MI != value))
				{
					this.OnMIChanging(value);
					this.SendPropertyChanging();
					this._MI = value;
					this.SendPropertyChanged("MI");
					this.OnMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="NChar(20)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomePhone", DbType="NChar(20)")]
		public string HomePhone
		{
			get
			{
				return this._HomePhone;
			}
			set
			{
				if ((this._HomePhone != value))
				{
					this.OnHomePhoneChanging(value);
					this.SendPropertyChanging();
					this._HomePhone = value;
					this.SendPropertyChanged("HomePhone");
					this.OnHomePhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPhone", DbType="NChar(20)")]
		public string WorkPhone
		{
			get
			{
				return this._WorkPhone;
			}
			set
			{
				if ((this._WorkPhone != value))
				{
					this.OnWorkPhoneChanging(value);
					this.SendPropertyChanging();
					this._WorkPhone = value;
					this.SendPropertyChanged("WorkPhone");
					this.OnWorkPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(100)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(100)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(100)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="NVarChar(50)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZIP", DbType="NVarChar(20)")]
		public string ZIP
		{
			get
			{
				return this._ZIP;
			}
			set
			{
				if ((this._ZIP != value))
				{
					this.OnZIPChanging(value);
					this.SendPropertyChanging();
					this._ZIP = value;
					this.SendPropertyChanged("ZIP");
					this.OnZIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="NVarChar(50)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employer", DbType="NVarChar(50)")]
		public string Employer
		{
			get
			{
				return this._Employer;
			}
			set
			{
				if ((this._Employer != value))
				{
					this.OnEmployerChanging(value);
					this.SendPropertyChanging();
					this._Employer = value;
					this.SendPropertyChanged("Employer");
					this.OnEmployerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
