    <link rel="stylesheet" href="/Content/jquery.mobile-1.4.5.min.css" />
    <link rel="stylesheet" href="/Assets/css/jqm-datebox.min.css"/>
    <link rel="stylesheet" href="/Assets/css/lessonweb.css" />
    <script src="/Assets/js/jquery-2.2.4.min.js"></script>
    <script src="/Scripts/jquery.mobile-1.4.5.min.js"></script>
    <script src="/Assets/js/pilotweb.js"></script>
    <script src="/Assets/js/jqm-datebox.core.min.js"></script>
    <script src="/Assets/js/jqm-datebox.mode.calbox.min.js"></script>
